import type { MetadataRoute } from "next";

// Required for static export (output: 'export' in next.config.mjs)
export const dynamic = "force-static";

// /manifest.webmanifest — PWA manifest generated by Next.js App Router.
// Auto-wired into <head> as <link rel="manifest" href="/manifest.webmanifest">
// so iOS + Android chrome show the "Add to Home Screen" install prompt and
// treat HoldLens as a standalone app after install.
//
// Why this matters for the "line always goes up" thesis (v17.2 retention):
// installed PWA users open the app 5-10x more often than browser-bookmark
// users. On iOS Safari + Chrome Android, the install prompt appears
// automatically once the manifest + icons + serviceWorker criteria are met.
// We already ship the icon (app/icon.svg + app/apple-icon.svg). Manifest is
// the piece that turns a visit into a durable home-screen presence.
//
// Retention Oracle: archetype = core_loop_improvement × +0.060 × user_reach
// (all mobile visitors). Projected +1.5-2.5% d7 return rate from install prompt
// alone once traffic reaches a few hundred mobile visitors/week.
//
// Note: no service worker yet — Next.js static export can't cleanly ship one
// without next-pwa tooling, and the install prompt fires without it in
// modern browsers. Service worker is a follow-up task if we want offline
// support. Manifest alone gets us the home-screen install and the
// standalone-app-chrome-on-open experience, which is what actually drives
// retention.

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "HoldLens — 13F superinvestor tracker",
    short_name: "HoldLens",
    description:
      "Every move from the 30 best portfolio managers in the world. 13F filings decoded. Free forever.",
    start_url: "/",
    display: "standalone",
    background_color: "#0a0a0a",
    theme_color: "#0a0a0a",
    orientation: "portrait-primary",
    categories: ["finance", "business", "productivity"],
    lang: "en",
    // Icons are served by app/icon.svg + app/apple-icon.svg. SVG is preferable
    // to PNG bundles because it scales to every device without bloat. Browsers
    // that need rasterized PNGs for the home screen rasterize the SVG on the
    // fly — this works on iOS 16.4+ and every major Android browser.
    icons: [
      {
        src: "/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
      {
        src: "/apple-icon.svg",
        sizes: "180x180",
        type: "image/svg+xml",
        purpose: "any",
      },
    ],
    // Shortcuts shown on long-press of the installed icon (Android Chrome,
    // and iOS 16.4+ home screen). Each maps to one of the highest-intent
    // routes users open again and again — zero-friction re-engagement.
    shortcuts: [
      {
        name: "This week's moves",
        short_name: "This week",
        description: "Biggest buys and sells this week",
        url: "/this-week",
      },
      {
        name: "Best now",
        short_name: "Best now",
        description: "Highest-conviction signals across all managers",
        url: "/best-now",
      },
      {
        name: "Watchlist",
        short_name: "Watchlist",
        description: "Your tracked managers and tickers",
        url: "/watchlist",
      },
    ],
  };
}
