/**
 * EDGAR 13F data loader — reads pre-fetched EDGAR data from JSON files
 * generated by scripts/fetch-edgar-13f.ts.
 *
 * Usage: import { EDGAR_MOVES, EDGAR_HOLDINGS, getEdgarHoldings } from "./edgar-data";
 *
 * The JSON files in data/ are committed to git. Run `npm run fetch-edgar`
 * to refresh them from SEC EDGAR (takes ~5 min, rate-limited).
 */

import type { Move, MoveAction, Quarter } from "./moves";

// Import pre-fetched JSON data
import edgarHoldings from "../data/edgar-holdings.json";
import edgarMoves from "../data/edgar-moves.json";
import edgarMeta from "../data/edgar-meta.json";

// ---------------------------------------------------------------------------
// Types for EDGAR JSON structure
// ---------------------------------------------------------------------------

interface EdgarFilingJson {
  managerSlug: string;
  cik: string;
  quarter: string;
  filingDate: string;
  reportDate: string;
  totalValueMn: number;
  holdingCount: number;
  holdings: {
    ticker: string;
    name: string;
    cusip: string;
    shares: number;
    valueMn: number;
    pctPortfolio: number;
  }[];
}

interface EdgarMoveJson {
  managerSlug: string;
  quarter: string;
  filedAt: string;
  ticker: string;
  name: string;
  action: string;
  deltaPct: number;
  shareChange: number;
  portfolioImpactPct: number;
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

/** All EDGAR holdings organized by filing (manager × quarter). */
export const EDGAR_FILINGS = edgarHoldings as EdgarFilingJson[];

/** Metadata about the last EDGAR fetch (timestamp, coverage, errors). */
export const EDGAR_META = edgarMeta as {
  fetchedAt: string;
  managersTotal: number;
  managersSuccess: number;
  filingsTotal: number;
  movesTotal: number;
  quartersSpanned: string[];
  errors: string[];
  unmappedCusips: string[];
};

/**
 * All EDGAR moves converted to the app's Move type.
 * Filtered to only include moves with valid ticker symbols (≤5 chars, no spaces).
 */
export const EDGAR_MOVES: Move[] = (edgarMoves as EdgarMoveJson[])
  .filter((m) => m.ticker.length >= 1 && m.ticker.length <= 5 && !m.ticker.includes(" "))
  .map((m) => ({
    managerSlug: m.managerSlug,
    quarter: m.quarter as Quarter,
    filedAt: m.filedAt,
    ticker: m.ticker,
    name: m.name,
    action: m.action as MoveAction,
    deltaPct: m.deltaPct,
    shareChange: m.shareChange,
    portfolioImpactPct: m.portfolioImpactPct,
  }));

/**
 * Get the latest EDGAR holdings for a specific manager.
 * Returns holdings sorted by portfolio weight, filtered to known tickers.
 */
export function getEdgarHoldings(managerSlug: string) {
  const filings = EDGAR_FILINGS
    .filter((f) => f.managerSlug === managerSlug)
    .sort((a, b) => b.quarter.localeCompare(a.quarter));

  if (filings.length === 0) return null;

  const latest = filings[0];
  return {
    quarter: latest.quarter,
    filingDate: latest.filingDate,
    totalValueMn: latest.totalValueMn,
    holdings: latest.holdings
      .filter((h) => h.ticker.length >= 1 && h.ticker.length <= 5 && !h.ticker.includes(" "))
      .map((h) => ({
        ticker: h.ticker,
        name: h.name,
        pct: h.pctPortfolio,
        sharesMn: Math.round(h.shares / 1_000_000 * 100) / 100,
        valueMn: h.valueMn,
      })),
  };
}

/**
 * Get EDGAR moves for a specific quarter, optionally filtered by manager.
 */
export function getEdgarMovesForQuarter(quarter: string, managerSlug?: string): Move[] {
  return EDGAR_MOVES.filter(
    (m) => m.quarter === quarter && (!managerSlug || m.managerSlug === managerSlug)
  );
}

/**
 * Get all quarters that have EDGAR data available.
 */
export function getEdgarQuarters(): string[] {
  return EDGAR_META.quartersSpanned;
}

/**
 * Check if EDGAR data is available for a specific manager.
 */
export function hasEdgarData(managerSlug: string): boolean {
  return EDGAR_FILINGS.some((f) => f.managerSlug === managerSlug);
}
