// Pure constants from signals.ts — safe to import from client components.
// lib/signals.ts re-exports + adds edgar-data-backed accessors.

export const MANAGER_QUALITY: Record<string, number> = {
  "warren-buffett":        10,
  "stanley-druckenmiller":  9,
  "seth-klarman":           9,
  "howard-marks":           9,
  "chris-hohn":             9,
  "chuck-akre":             9,
  "terry-smith":            9,
  "stephen-mandel":         9,
  "bill-ackman":            8,
  "carl-icahn":             8,
  "li-lu":                  8,
  "joel-greenblatt":        8,
  "andreas-halvorsen":      8,
  "jeffrey-ubben":          8,
  "lee-ainslie":            8,
  "polen-capital":          8,
  "david-tepper":           9,
  "chase-coleman":          8,
  "john-armitage":          9,
  "david-rolfe":            9,
  "francois-rochon":        9,
  "dev-kantesaria":         9,
  "william-von-mueffling":  8,
  "tom-slater":             8,
  "prem-watsa":             7,
  "bill-nygren":            7,
  "glenn-greenberg":        7,
  "david-einhorn":          7,
  "michael-burry":          7,
  "monish-pabrai":          6,
};
